export const diamondData = [
  {
    id: 1,
    karat: "18kt",
    color: "Yellow",
    clarity: "VVS-VS1-E-F",
    price: 60257,
    priceWithTax: 62065,
    stone: "Pearl-White",
    code: "VS-EF",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 2,
    karat: "14kt",
    color: "Yellow",
    clarity: "VVS-VS1-E-F",
    price: 40823,
    priceWithTax: 42048,
    stone: "CZ-Blue",
    code: "VS-SI-EF",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 3,
    karat: "22kt",
    color: "Yellow",
    clarity: "VS2-GH",
    price: 82781,
    priceWithTax: 85264,
    stone: "CZ-pd",
    code: "GH",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 4,
    karat: "P950",
    color: "Silver",
    clarity: "GEO",
    price: 2088,
    priceWithTax: 2151,
    stone: "EB-GEO",
    code: "Brown",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 5,
    karat: "18kt",
    color: "Rose",
    clarity: "SI1-HI",
    price: 53200,
    priceWithTax: 54896,
    stone: "CZ-Green",
    code: "HI",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 6,
    karat: "14kt",
    color: "White",
    clarity: "VVS-EF",
    price: 39500,
    priceWithTax: 40785,
    stone: "Opal",
    code: "EF",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 7,
    karat: "22kt",
    color: "Rose",
    clarity: "VS1-G",
    price: 91500,
    priceWithTax: 94145,
    stone: "CZ-Yellow",
    code: "G",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 8,
    karat: "P950",
    color: "Silver",
    clarity: "GEO",
    price: 2450,
    priceWithTax: 2524,
    stone: "EB-Green",
    code: "Grey",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 9,
    karat: "18kt",
    color: "White",
    clarity: "SI2-JK",
    price: 47200,
    priceWithTax: 48616,
    stone: "Pearl-Pink",
    code: "JK",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 10,
    karat: "14kt",
    color: "Yellow",
    clarity: "VS2-FG",
    price: 35000,
    priceWithTax: 36155,
    stone: "CZ-Black",
    code: "FG",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 11,
    karat: "22kt",
    color: "Yellow",
    clarity: "VVS1-DE",
    price: 88800,
    priceWithTax: 91464,
    stone: "CZ-White",
    code: "DE",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 12,
    karat: "18kt",
    color: "Rose",
    clarity: "VS-SI",
    price: 56000,
    priceWithTax: 57768,
    stone: "Moissanite",
    code: "SI",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
  {
    id: 13,
    karat: "P950",
    color: "Silver",
    clarity: "GEO",
    price: 2300,
    priceWithTax: 2376,
    stone: "EB-Blue",
    code: "Blue",
    img: `https://cdn.caratlane.com/media/catalog/product/S/R/SR03489-WGP900_1_lar.jpg`,
  },
];